### ISSUE TITLE
Support multiple file bundles

### ISSUE THREAD

**Issue by mikeal** [mattdesl/budo#202] opened 2017-03-17 21:46 UTC
It's pretty common to need a Service Worker or Web Worker in another file.

What I want is something like `budo index.js:bundle.js worker.js:sw.js` that would compile multiple end points.

**Comment by mattdesl** [comment] 2017-03-17 21:57
Sounds good with me. 👍 Just wonder how to handle the current `--serve` API.

**Comment by mattdesl** [comment] 2017-04-21 16:01
Closing since this is a duplicate of #139. Still not sure how to fit this into the architecture of budo (and dealing with multiple watchify instances).

**Closed by mattdesl** 2017-04-21 16:01 UTC
