### ISSUE TITLE
--build or similar for a one-time build

### ISSUE THREAD

**Issue by wbinnssmith** [mattdesl/budo#92] opened 2015-10-14 20:33 UTC
Budo could provide a `--build`, `-o` option or similar that does a one-off build that outputs `index.html`, the browserify entry point(s), and other accessible static media to an output. Would make for an easy transition from development server to a generated static site that's deployable, all from using the same cli switches passed to budo.

If this is out of scope for budo I definitely understand.

**Comment by mattdesl** [comment] 2015-10-14 20:41
Check out discussion here: #60. Would be a nice feature.

I think it's mostly a matter of:

- figuring out how to get it working with uglify and other "production level" transforms/tools
- coming up with a nice way to keep your package.json DRY 
- thinking about how the API `middleware` option might be affected
  - i.e. what to do with custom routes

**Comment by mattdesl** [comment] 2016-01-01 20:00
Closing this since it's basically a duplicate of #60 .

**Closed by mattdesl** 2016-01-01 20:00 UTC
Labels: enhancement, help wanted
