### ISSUE TITLE
Expose a way to handle unhandled requests

### ISSUE THREAD

**Issue by edenh** [mattdesl/budo#52] opened 2015-08-05 01:19 UTC
The use case I'm seeing is using `react-router`'s [`historyLocation`](http://rackt.github.io/react-router/#HistoryLocation) and developing with budo locally. It would be useful to create a custom route for unhandled requests so that refreshes don't break.

**Comment by bendrucker** [comment] 2015-08-05 02:18
Dupe of #41

**Closed** 2015-08-05 16:38 UTC
