### ISSUE TITLE
User internal-ip instead of localhost

### ISSUE THREAD

**Issue by MikkoH** [mattdesl/budo#65] opened 2015-09-23 17:34 UTC
It might be handy to use this your machine internal ip instead of localhost to open the page.

https://www.npmjs.com/package/internal-ip

**Comment by mattdesl** [comment] 2015-09-23 18:30
dupe of #39 :smile:

I'm :+1: to this feature but last time I attempted to use `internal-ip`, it was causing `http://localhost:9966/` to 404. Ideally there is a solution that allows both addresses to resolve to the same thing; maybe somebody more familiar with Node's `http` stuff could chime in.

**Comment by yoshuawuyts** [comment] 2015-09-24 00:02
This could work:
```js
const http = require('http')
http.createServer().listen(() => console.log(this.address().address)
```
In the `.listen()` callback you can retrieve the IP value. The value returned here is either a full IP or `::` (IPv6, [docs](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)). When `::` is returned you could probably check for that and resolve it to `localhost` or `127.0.0.1`. 

I've looked into this for [server-summary](https://github.com/yoshuawuyts/server-summary) before but always got `::` as a response so I'm not sure if this'll work. I hope it's useful regardless (':

- [node/docs/http:server.listen](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)
- [SO: how to get the ip addres of a http server](http://stackoverflow.com/questions/24378272/node-js-how-to-get-the-ip-address-of-http-server-listening-on-a-specific-port)

**Comment by mattdesl** [comment] 2015-09-24 13:11
Ah, so basically the solution is just to pass `undefined` for host to the `listen` function, and this will allow `localhost` and internal IP to both act the same way. 

I am thinking if no `--host` is specified, this will be default, and the following will print:

```
Server started at http://localhost:9966/
Internal IP is http://192.168.1.1:9966/
```

I'll keep `uri` pointing to localhost, and `--open` will open that. The internal IP is just logged for user friendliness.

**Comment by MikkoH** [comment] 2015-09-24 13:25
Minor thing but ios9 has implemented handoff properly now. When you double click the home button it will ask if you want to open the currently open site on mobile that is open on desktop.

So if the actual ip is opened in browser that handoff will be really seamless and that's the whole reason to show internal ip anyway.

**Comment by MikkoH** [comment] 2015-09-24 13:26
Basically you'd never have to type ips on device.

**Comment by mattdesl** [comment] 2015-09-24 13:48
Wow that's neat. 

So how about: when no `--host` is given, `ev.host` will be the internal IP. This will affect the `'connect'` event and also open the browser to the internal IP. Users can still use `--host=localhost` for the old behaviour.

**Comment by mattdesl** [comment] 2015-09-24 15:42
This feature should be in latest `next` branch. I'll be merging next with master later today since things seem pretty stable.

**Closed by mattdesl** 2015-09-24 15:42 UTC

**Comment by MikkoH** [comment] 2015-09-24 20:20
:+1:
