### ISSUE TITLE
adds empty `style` tag in head (even if custom index is used)

### ISSUE THREAD

**Issue by tunnckoCore** [mattdesl/budo#68] opened 2015-09-24 20:16 UTC
just using this index, and it seems that when load it `budo` adds empty style tag. Cant realize from where and why.
```html
<!doctype html>
<html>
<head>
  <title>foo</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="main.css">
</head>
<body>
  <script src="bundle.js"></script>
</body>
</html>

**Comment by mattdesl** [comment] 2015-09-24 20:53
It looks like it's finding a local `index.html` with `<title>foo</title>` (not something budo adds).

`budo` will look for an `index.html` in the initial "static" directory, so:

```sh
budo index.js | garnish
```

Will look in `process.cwd()` for an `index.html`.

And:

```sh
budo src/index.js --dir static/
```

Will look for `static/index.html`.

**Comment by tunnckoCore** [comment] 2015-09-24 21:46
I know that it also works without the need of index.html in the disk. Problem is that I need index, because there's no options for css and title (see #67). And so when i look through dev tools when i load the url, there's empty style tag always.

actuals

**public/index.html**

```html
<!doctype html>
<html>
<head>
  <title>Charlike Mike Reagent (@tunnckoCore)</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="main.css">
</head>
<body>
  <script src="bundle.js"></script>
</body>
</html>
```

**index.js** in root

```js
console.log(actual)
```

command
```
budo index.js:bundle.js --live --dir public | garnish
```

the served html
```html
<!doctype html>
<html>
<head>
  <title>foo</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="http://localhost:9966/main.css?livereload=1443130457616">
  <style type="text/css"></style> <!-- i'm talking for this one -->
</head>
<body>
  <script type="text/javascript" src="http://localhost:35729/livereload.js?snipver=1"></script>
  <script src="bundle.js"></script>
</body>
</html>
```

Would be useful to have `--css` (for css path, as in `serves`) and `--title`, to not need adding boilerplate index.html like that.

**Comment by mattdesl** [comment] 2015-09-25 02:14
I can't reproduce your problem with `budo@next`. It looks like your browser or some extension is adding the extra `<style>` tag. 

See [these tests](https://github.com/mattdesl/budo/blob/edf7199be00bd0d883da264e100236e1bb59a561/test/test-live.js#L110-L116) or run your own request to find out what content budo is serving, without the bloat of your browser:

`server.js`

```js
var request = require('got')

require('budo').cli(process.argv.slice(2))
  .on('connect', function (ev) {
    request(ev.uri + 'index.html', function (err, body) {
      if (err) {
        console.error(err)
      } else {        
        console.log(body)
      }
    })
  })
```

```sh
node server.js index.js:bundle.js --live --dir public | garnish
```

With `public/index.html` and your code, I get this:

```html
<!doctype html>
<html>
<head>
  <title>Charlike Mike Reagent (@tunnckoCore)</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="main.css">
</head>
<body><script type="text/javascript" src="http://localhost:35729/livereload.js?snipver=1"></script>
  <script src="bundle.js"></script>
</body>
</html>
```

The only thing that should change is the added `livereload.js` script (and only when `--live` is passed).

It would not be hard to add `--title` and `--css`, and it seems in line with the eventual goals in #60.

**Comment by tunnckoCore** [comment] 2015-09-25 17:22
Hm, maybe. I'll try. 

> It would not be hard to add --title and --css, and it seems in line with the eventual goals in #60.

Yea it would be just this change in `lib/server.js`

```js
   var stream = opts.defaultIndex || defaultIndex
    stream({
      entry: entrySrc,
      title: opts.title, // added
      css: opts.css // added
    }).pipe(res)
```

**Comment by mattdesl** [comment] 2015-09-25 17:37
For `--css` it would probably make sense to handle "entry mapping" in the same way as JS files.

This way a user could do this:

```sh
budo src/index.js:bundle.js --css src/main.css:main.css
```

This makes it easy to use the same `index.html` in development and production (e.g. gh-pages), but have the production use uglify and compression.

**Comment by tunnckoCore** [comment] 2015-09-25 17:39
:+1: yea, looks better.

**Comment by mattdesl** [comment] 2015-09-28 13:40
Closing since this issue is related to the browser, not budo.

**Closed by mattdesl** 2015-09-28 13:40 UTC
Labels: invalid
