### ISSUE TITLE
No livereload with directory start

### ISSUE THREAD

**Issue by gabrielstuff** [mattdesl/budo#155] opened 2016-04-30 15:40 UTC
Version : "budo": "8.2.2"
Chrome 50.0.2661.86 
Env: Electron: v0.37.7 - node v5.10.0

I'm using Budo with its API.

I'm running : 

```
budo('', {
        live: true, // setup live reload
        dir: path
      }).on('connect', function(ev) {
        console.log('Server running on %s', ev.uri)
        console.log('LiveReload running on port %s', ev.livePort)
        window.webContents.send('server-started', {url: ev.uri, name: path, checked:true})
      }).on('update', function(buffer) {
        console.log('bundle - %d bytes', buffer.length)
      })
```

Path is a directory. Budo serve everything correctly. Unfortunately altering the .html or .css file does not seems to reload the content. I have to manually reload the page. 

Running budo from command line : `budo --live --dir=MYPATH` works perfectly.

**Comment by mattdesl** [comment] 2016-05-01 01:31
I just tried and things seem fine here. Can you put together a test case so that I can reproduce the issue? Thanks. 😄

**Comment by gabrielstuff** [comment] 2016-05-01 19:15
Well, it must be something with my computer :( 
Just tried the budo command line I posted and it doesn't work anymore : `budo --live --livePort=34543` or `budo --dir=. --live` or `budo --dir=MYPATH --live`
The example is as it : 
```
'use strict'

const budo = require('budo')
let path = 'pathgoehere'

budo('', {
  live: true, 
  dir: path
}).on('connect', function (ev) {
  console.log('Server running on %s', ev.uri)
  console.log('LiveReload running on port %s', ev.livePort)
}).on('update', function (buffer) {
  console.log('bundle - %d bytes', buffer.length)
})
```

**Comment by pguth** [comment] 2016-05-11 11:08
I just ran into the same problem:
```sh
> budo --live --dir=. --debug --host localhost index.js:bundle.js

[0000] info  Server running at http://localhost:9966/ (connect)
[0000] info  LiveReload running on 35729
[0001] 58ms       1610B (browserify)
[0005] 7ms        1610B GET    200 /bundle.js
# Meanwhile `/bundle.js` got altered.
[0011] 3ms        1610B GET    200 /bundle.js
[0012] 1ms        1610B GET    200 /bundle.js
```

With and without `dir` it does not re-generate the bundle.js but **just delivers the result of the initial compilation** 😿.

**Comment by mattdesl** [comment] 2016-06-17 18:52
Sorry, your message slipped through the cracks of my email it seems.

Can you let me know what OS you are using? I'm using the same command on the same node/npm versions and I can't reproduce any problems. I'm on OSX 10.11.4.

**Comment by pguth** [comment] 2016-06-17 20:09
Np, thanks @mattdesl. I am on: OSX 10.11.5

**Comment by mattdesl** [comment] 2017-01-13 14:25
For those experiencing LiveReload issues, you can try the WIP branch here which replaces tiny-lr with a custom WebSocket backend:

https://github.com/mattdesl/budo/issues/194#issuecomment-271034242

**Comment by mattdesl** [comment] 2017-04-21 15:56
Should probably be fixed with latest 10.x release. Please open a new issue if there's any more LiveReload bugs.

**Closed by mattdesl** 2017-04-21 15:56 UTC
